name: box2d
version: 0.0.7
description: A port of the popular Box2D physics engine to Dart.
author: Dominic Hamon <dominic@google.com>
homepage: http://code.google.com/p/dartbox2d
dependencies:
  args: 0.2.10+1
  vector_math:
    git: git://github.com/johnmccutchan/DartVectorMath.git

